### PR TITLE
Fix missing placeholders for submodules

### PR DESCRIPTION
**Pull request by proletarius101**
The following submodules lack placeholders, which is problematic for many build procedures (e.g. Flatpak), and is not really legit, while others having their placeholders:
````
app/extensions/extensions-manager
vendor/extensions/extensions-manager
````

Related issue: https://github.com/flatpak/flatpak-builder-tools/issues/182

### CODE REVIEW

**Comment by proletarius101** [comment]
Hi @baptiste-grob, can you merge this PR which I think is a easy fix?

**Comment by baptiste-grob** [comment]
Hey @proletarius101, sorry for the late response! Can you tell me what you mean by placeholders? The modules are already referenced in `.gitmodules` as far as I'm aware.

Also can you please remove the `package-lock.json` file as we actually use yarn 😅

**Comment by proletarius101** [comment]
> Also can you please remove the package-lock.json file as we actually use yarn sweat_smile

Oh sorry, that was a mistake. It was supposed to be my local experiment. Dropped that commit.

> Can you tell me what you mean by placeholders? The modules are already referenced in .gitmodules as far as I'm aware.

A git submodule consists of two parts:
- A record in `.gitmodules`
- A placeholder file in the path of the modules, e.g.
  ````
  $ git diff --cached DbConnector
  diff --git a/DbConnector b/DbConnector
  new file mode 160000
  index 0000000..c3f01dc
  --- /dev/null
  +++ b/DbConnector
  @@ -0,0 +1 @@
  +Subproject commit c3f01dc8862123d317dd46284b05b6892c7b29bc
  ````
  You can read more about that here: https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by baptiste-grob** [comment]
Ah okay, that makes sense, thank you for taking the time to explain that to me!

**Review by baptiste-grob — APPROVED** [review]

**Pull request merged**
