### PR TITLE
fix(desktop): search highlight on pagination

### PR DESCRIPTION
**Pull request by jh-code**
Referencing issue standardnotes/bounties#20

Just triggering it on pagination caused some issues because typing in the search box can trigger it as well so I added a flag to prevent that.

### CODE REVIEW

**Comment by mobitar** [comment]
What about checking if `this.noteFilter.text` is empty or not on pagination instead of creating a new var `searchEntered`?

**Comment by jh-code** [comment]
Pagination can happen multiple times while typing into the search box, so checking if the filter is empty or not wouldn't work. The issue arises when you enter some text, press enter, and then try to search for a new string. After each character press that triggers pagination, it will unfocus on the input. The flag prevents all of that and only lets it run after someone has search and not entered anything new into the search box.

**Comment by mobitar** [comment]
Oh I see, `searchEntered` means "search has submitted". I thought it meant "user has entered into search", but it means "user has entered out of search". Can we rename that var to something like `searchReturned` or `searchSubmitted`?

**Comment by jh-code** [comment]
I was thinking about renaming that before honestly, I figured that name wouldn't be obvious. Nonetheless, just renamed it to `searchSubmitted` and pushed it.

**Comment by mobitar** [comment]
Great, thanks. Also, have you confirmed whether the ordering of 

```

**Comment by jh-code** [comment]
Good call, I wasn't able to notice any issues, but just to be safe I added that change as well.

**Comment by mobitar** [comment]
Nice work, thanks @jh-code!

**Pull request merged**
