### PR TITLE
Fixed some vulnerabilities in packages

### PR DESCRIPTION
**Pull request by gustawdaniel**
Before: found 324 vulnerabilities (5 low, 315 moderate, 4 high)
Now: found 3 low severity vulnerabilities

### CODE REVIEW

**Comment by mobitar** [comment]
You would have to commit your package.json. package-lock.json is generated based on package.json.

**Comment by gustawdaniel** [comment]
But I do not want to change any version of packages in `package.json`. I only run the command:

```
npm audit fix
```

Notice that all packages are installed based on the content of `package-lock.json`.

**Comment by mobitar** [comment]
I don't think updating dependencies of dependencies is the right idea. You'd have to update the parent, if there is an update available. You can't be sure that the sub-dependency updates don't have adverse affects on the parent.

https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities

**Comment by gustawdaniel** [comment]
Ok.

**Pull request closed without merging**
